### ISSUE TITLE
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

### ISSUE THREAD

**Issue by kiliczsh** [kiliczsh/sandik#8]
cc: @BYK 

```console
INFO:root:Sleeping before retry for https://api-sonuc.oyveotesi.org/api/v1/cities/65/districts/819/neighborhoods/42111/schools (try: 6)...
INFO:root:Sleeping before retry for https://api-sonuc.oyveotesi.org/api/v1/cities/65/districts/819/neighborhoods/42069/schools (try: 6)...
INFO:root:Sleeping before retry for https://api-sonuc.oyveotesi.org/api/v1/cities/65/districts/818/neighborhoods/42045/schools (try: 6)...
Traceback (most recent call last):
  File "/Users/xxx/Development/sandik/main.py", line 272, in <module>
    asyncio.run(main())
  File "/Users/xxx/.pyenv/versions/3.11.1/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/xxx/.pyenv/versions/3.11.1/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/xxx/Development/sandik/main.py", line 258, in main
    city = await City(
           ^^^^^^^^^^^
  File "/Users/xxx/Development/sandik/main.py", line 186, in download
    self.districts = await asyncio.gather(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Development/sandik/main.py", line 139, in download
    self.neighborhoods = await asyncio.gather(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Development/sandik/main.py", line 103, in download
    for school in await self.fetch(self.schools_url)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Development/sandik/main.py", line 26, in fetch
    async with self.session.get(url, raise_for_status=True) as response:
  File "/Users/xxx/Development/sandik/.venv/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/Users/xxx/Development/sandik/.venv/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/Users/xxx/Development/sandik/.venv/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Development/sandik/.venv/lib/python3.11/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

**Comment by BYK** [comment]
Heh, I think they don't want the traffic 😅
